services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gameon
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  lora-handler:
    build: ./lora-handler
    container_name: lora_handler
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: gameon
      USB_PORT: /dev/ttyUSB0
      USB_BAUDRATE: 115200
      PYTHONUNBUFFERED: 1
    volumes:
      - ./lora-handler:/app
    restart: always
    devices:
      - /dev/ttyUSB1:/dev/ttyUSB0

  webserver:
    build: ./webserver
    container_name: gameon_web
    depends_on:
      - mysql
    ports:
      - "8888:80"
    environment:
      DB_HOST: mysql
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: gameon
    volumes:
      - ./webserver:/app
    restart: always

volumes:
  mysql_data:
